version: '3.8'

services:
  # Your Next.js + Payload App Service
  app:
    build: .
    container_name: my_payload_app
    ports:
      # Exposes your app's port 3000 to the host machine's port 3000
      - "3000:3000"
    environment:
      # You must provide the full connection string to your separate database
      - DATABASE_URL=${DATABASE_URL}
      - PAYLOAD_SECRET=${PAYLOAD_SECRET}
      # This should be your server's public domain name or IP
      - NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL}
    volumes:
      # Maps the named volume 'payload_media' to the '/app/media' directory inside the container
      - payload_media:/app/media
    restart: unless-stopped

# Top-level volumes definition where Docker will manage the persistent media data
volumes:
  payload_media:
