version = 4.2.0
archive_dir = /etc/letsencrypt/archive/finn-ob.ca
cert = /etc/letsencrypt/live/finn-ob.ca/cert.pem
privkey = /etc/letsencrypt/live/finn-ob.ca/privkey.pem
chain = /etc/letsencrypt/live/finn-ob.ca/chain.pem
fullchain = /etc/letsencrypt/live/finn-ob.ca/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 60a1f1d49118f08ac49c4415367b2f3f
authenticator = webroot
webroot_path = /var/www/html,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
finn-ob.ca = /var/www/html
www.finn-ob.ca = /var/www/html
